---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - import
  # https://github.com/gajus/eslint-plugin-flowtype
  - flowtype
  - flow
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'airbnb'
  - 'prettier'
  - 'prettier/flowtype'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
  no-console: 0
